# Generated by Django 4.2.30 on 2026-06-30 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0003_alter_orderitem_current_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_point_from', models.CharField(choices=[('S1_PICKUP', 'S1 — Pickup (Hospital)'), ('S2_RECEIVED', 'S2 — Received at Plant'), ('S3_DISPATCH', 'S3 — Dispatch (Plant)'), ('S4_DELIVERY', 'S4 — Delivery (Hospital)')], max_length=20)),
                ('scan_point_to', models.CharField(choices=[('S1_PICKUP', 'S1 — Pickup (Hospital)'), ('S2_RECEIVED', 'S2 — Received at Plant'), ('S3_DISPATCH', 'S3 — Dispatch (Plant)'), ('S4_DELIVERY', 'S4 — Delivery (Hospital)')], max_length=20)),
                ('expected_count', models.PositiveIntegerField()),
                ('received_count', models.PositiveIntegerField()),
                ('missing_tags', models.JSONField(default=list)),
                ('is_matched', models.BooleanField(default=False)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_logs', to='hospital.laundryorder')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='RFIDScanEvent',
            fields=[
                ('scan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_number', models.CharField(db_index=True, max_length=50)),
                ('scan_point', models.CharField(choices=[('S1_PICKUP', 'S1 — Pickup (Hospital)'), ('S2_RECEIVED', 'S2 — Received at Plant'), ('S3_DISPATCH', 'S3 — Dispatch (Plant)'), ('S4_DELIVERY', 'S4 — Delivery (Hospital)')], max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('location_note', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='hospital.laundryorder')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='hospital.orderitem')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scanned_at'],
                'indexes': [models.Index(fields=['tag_number', 'scan_point'], name='rfid_rfidsc_tag_num_ef46e2_idx'), models.Index(fields=['order', 'scan_point'], name='rfid_rfidsc_order_i_9f8498_idx')],
            },
        ),
    ]
