# Generated by Django 4.2.30 on 2026-06-30 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('tag_number', models.CharField(blank=True, max_length=50)),
                ('notification_type', models.CharField(choices=[('MISSING_ITEM', 'Missing Item'), ('TRANSIT_LOSS', 'Transit Loss'), ('DELIVERY_COMPLETE', 'Delivery Complete'), ('ORDER_RECEIVED', 'Order Received')], default='MISSING_ITEM', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
