# Generated by Django 5.2.15 on 2026-06-30 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_deliveryprofile_hospitalprofile_hospitaldepartment_and_more'),
        ('hospital', '0002_orderitem_last_scanned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('PICKUP', 'Pickup (S1)'), ('DELIVERY', 'Delivery (S4)')], max_length=10)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='ASSIGNED', max_length=15)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.deliveryprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_jobs', to='hospital.laundryorder')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(fields=('order', 'job_type'), name='unique_job_per_order_type')],
            },
        ),
    ]
