# Generated by Django 5.2.15 on 2026-06-30 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('RECEIVED', 'Received'), ('SORTING', 'Sorting'), ('WASHING', 'Washing'), ('DRYING', 'Drying'), ('FOLDING', 'Folding'), ('READY', 'Ready for Dispatch')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='hospital.orderitem')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MissingItemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('last_stage', models.CharField(choices=[('RECEIVED', 'Received'), ('SORTING', 'Sorting'), ('WASHING', 'Washing'), ('DRYING', 'Drying'), ('FOLDING', 'Folding'), ('READY', 'Ready for Dispatch')], max_length=20)),
                ('last_updated_at', models.DateTimeField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_assigned', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='hospital.orderitem')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerItemAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_first_worker', models.BooleanField(default=False)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_assignments', to='hospital.orderitem')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assigned_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_first_worker', True)), fields=('order_item',), name='unique_first_worker_per_item')],
            },
        ),
    ]
