# Generated by Django 4.2.30 on 2026-07-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingitemalert',
            name='last_stage',
            field=models.CharField(choices=[('WITH_HOSPITAL', 'With Hospital'), ('PICKUP_SCANNED', 'Pickup Scanned (S1)'), ('IN_TRANSIT_OUTBOUND', 'In Transit — Outbound'), ('AT_LAUNDRY', 'At Laundry (S2)'), ('RECEIVED_AT_PLANT', 'Received at Plant (S2)'), ('TRANSIT_LOSS_FLAG', 'Transit Loss — Flagged'), ('WASHED', 'Washed'), ('IN_TRANSIT_RETURN', 'In Transit — Return'), ('DISPATCHED', 'Dispatched (S3)'), ('DELIVERED', 'Delivered (S4)'), ('COMPLETED', 'Completed')], max_length=25),
        ),
    ]
