# Generated by Django 5.2.15 on 2026-06-30 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_deliveryprofile_hospitalprofile_hospitaldepartment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalPartnerSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_selections', to='accounts.deliveryprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_selections', to='accounts.hospitalprofile')),
                ('laundry_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_selections', to='accounts.laundryprofile')),
            ],
            options={
                'ordering': ['-selected_at'],
            },
        ),
        migrations.CreateModel(
            name='LaundryOrder',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PICKUP_DONE', 'Pickup Done'), ('AT_LAUNDRY', 'At Laundry'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('FLAGGED', 'Flagged')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('delivery_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.deliveryprofile')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.hospitaldepartment')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.hospitalprofile')),
                ('laundry_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.laundryprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('item_type', models.CharField(choices=[('BEDSHEET', 'Bedsheet'), ('PILLOW_COVER', 'Pillow Cover'), ('PATIENT_GOWN', 'Patient Gown'), ('OT_DRAPE', 'OT Drape'), ('OTHER', 'Other')], default='BEDSHEET', max_length=20)),
                ('current_status', models.CharField(choices=[('WITH_HOSPITAL', 'With Hospital'), ('PICKUP_SCANNED', 'Pickup Scanned (S1)'), ('AT_LAUNDRY', 'At Laundry (S2)'), ('WASHED', 'Washed'), ('DISPATCHED', 'Dispatched (S3)'), ('DELIVERED', 'Delivered (S4)'), ('COMPLETED', 'Completed')], default='WITH_HOSPITAL', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='accounts.hospitaldepartment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hospital.laundryorder')),
            ],
            options={
                'ordering': ['tag_number'],
            },
        ),
    ]
