# Generated by Django 5.2.15 on 2026-06-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
